# 基础镜像
FROM node:16-alpine

# 工作目录
WORKDIR /app

# 复制项目文件
COPY . .

# 安装依赖
RUN npm install

# 使用 nginx 提供服务
FROM nginx:alpine
COPY --from=0 /app/dist /usr/share/nginx/html

# 暴露端口
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]